global using GamersParadise.DAL;
global using GamersParadise.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using GamersParadise.Areas.Identity.Data;
global using Microsoft.AspNetCore.Identity;
global using System.Text.Json;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;